#Get ubuntu image
FROM ubuntu:20.04

#Created by Donald DeWitt 2021
MAINTAINER don

#Resynchronize the package index files from their sources
RUN apt-get update

#Install Python3
RUN apt-get install python3 -y
